//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    
    public partial class SHOW_USER_METAS_Result1
    {
        public int USER_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string SEX { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public System.DateTime START_TIME { get; set; }
        public string NUMBER_PHONE { get; set; }
        public string SENIORITY { get; set; }
        public string NATIVE_LAND { get; set; }
        public string LITERACY { get; set; }
    }
}
