//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SYSTEM_DATABASEEntities : DbContext
    {
        public SYSTEM_DATABASEEntities()
            : base("name=SYSTEM_DATABASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANG_CHAM_CONG> BANG_CHAM_CONG { get; set; }
        public virtual DbSet<BANG_LUONG> BANG_LUONG { get; set; }
        public virtual DbSet<LIST_CONTROLLERS> LIST_CONTROLLERS { get; set; }
        public virtual DbSet<LIST_PERMISSIONS> LIST_PERMISSIONS { get; set; }
        public virtual DbSet<USER_PERMISSION> USER_PERMISSION { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<GHI_CHU_CONG_VIEC> GHI_CHU_CONG_VIEC { get; set; }
    }
}
